<!DOCTYPE html PUBLIC "-//W3C//DTD XHTML 1.0 Strict//EN" "http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd"> 
 
<html xmlns="http://www.w3.org/1999/xhtml" xmlns:fb="http://www.facebook.com/2008/fbml"> 
<head profile="http://gmpg.org/xfn/11"> 
<meta http-equiv="Content-Type" content="text/html; charset=UTF-8" /> 
 
<title> Example Application - <?php echo $this->getTitle() ?> </title> 
</head>
<body>

    <div id="header">
        <h1>Header - <?php echo $this->getTitle() ?> </h1>
    </div>
    
    <div id="content">
        <?php echo $this->getChild() ?>
    </div>
    
    <div id="footer">
        &copy; Copy copian
    </div>
    
</body>
</html>

